### PR TITLE
Add MRI 2.2.0 to Travis configuration

### PR DESCRIPTION
**Pull request by packetmonkey**
If you are ok with officially supporting MRI 2.2.0 this PR adds it to the travis build as a required pass.

### CODE REVIEW

**Comment by packetmonkey** [comment]
The build failure on 2.2.0 can be fixed by adding the 'test-unit' gem as a development dependency, but I didn't want to make that change without a :+1: from you first. Let me know if you want me to add the change.

Thanks

**Comment by evolve75** [comment]
Sure Evan,  

Please add the `test-unit` gem as a development dependency in `rubytree.gemspec`, and also add a customized requirement in the `Gemfile`, to require this gem only for MRI > 2.2.x. That way we can avoid having to load the library where it already exists.

**Comment by packetmonkey** [comment]
Interestingly the older platforms are breaking with the newer platform option. I'm not very familiar with that configuration option so I presume I am doing something wrong, I looked though the [gemfile manpage](http://bundler.io/man/gemfile.5.html) for what to use but would be grateful for a pointer.

**Comment by evolve75** [comment]
Hmm.  Looks like Bundler does not yet support MRI 2.2.0.  Might have to wait on this one.

**Comment by evolve75** [comment]
Evan,

I fixed the issue (was essentially a development vs. test dependency on the `test-unit` gem). The build is now working fine on all versions, including 2.2.0.

**Pull request closed without merging**
